apiVersion: v1
kind: Pod
metadata:
  name: debugclient
  labels:
    app: debugclient
spec:
  containers:
  - image: "alpine:3.4"
    name: alpine
    command:
      - 'sleep'
      - '86400'
  - image: quay.io/plange/packetbeat:1.2.3
    imagePullPolicy: Always
    name: packetbeat
    securityContext:
      privileged: true
    env:
    - name: SHIPPER_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: LOGSTASH_HOSTS
      value: logs.default:5044
    - name: HTTP_SEND_REQUEST
      value: "true"
    - name: HTTP_SEND_RESPONSE
      value: "true"
    - name: HTTP_INCLUDE_BODY_FOR
      value: "'text/html', 'text/xml'"
    - name: REDIS_SEND_REQUEST
      value: "true"
    - name: REDIS_SEND_RESPONSE
      value: "true"
    - name: HTTP_SEND_ALL_HEADERS
      value: "false"
